spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  jpa:
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  redis:
    host: 127.0.0.1
    port: '6379'
  datasource:
    url: jdbc:mysql://localhost:3306/my_alley?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: '0104'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

server:
  servlet:
    session:
      timeout: 10m
logging:
  level:
    sql: ERROR
    root: INFO

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

